learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls'), namespace='learning_logs')),
    path('', include(('users.urls'), namespace='users')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page 
    url(r'^$', views.index, name='index'),

    # Show all medications
    url(r'^medications/$', views.topics, name='medications'),

    # Show information for a single medication
    url(r'^medications/(?P<topic_id>\d+)/$', views.topic, name='medication'),

    # Show information to refill a medication
    url(r'^medications/refills/(?P<zip_code>\d+)/(?P<medication_id>\d+)/$', views.refill, name='refill'),

    # Page for adding new medications
    url(r'^new_medication/$', views.new_topic, name='new_medication'),

    # Page with team member information
    url(r'^support/$', views.support, name='support'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    # Login page 
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from datetime import datetime
from datetime import timedelta

class Topic(models.Model):
    """A topic the user is learning about"""
    name = models.CharField(max_length=200, default=None)
    prescriber = models.CharField(max_length=200, default=None)
    pharmacy = models.CharField(max_length=200, default=None)
    price = models.FloatField()
    dose = models.FloatField()
    dose_units = models.CharField(max_length=100, default=None)
    pill_count = models.IntegerField()
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def expiration_status(self):
        if datetime.now().date() > self.expiration_date:
            return 'danger'
        elif datetime.now().date() > self.expiration_date - timedelta(days=15):
            return 'primary'
        else:
            return 'success'

    @property
    def expiration_text(self):
        if datetime.now().date() > self.expiration_date:
            return 'Expired'
        elif datetime.now().date() > self.expiration_date - timedelta(days=15):
            return 'Expiring'
        else:
            return 'Valid'

    def __str__(self):
        """Return a string representation of the model"""
        return self.name

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name', 'dose', 'dose_units', 'pill_count', 'prescriber', 'pharmacy', 'price', 'expiration_date']
        labels = {'name': 'Medication', 'dose_units': 'Dose Units', 'pill_count':'Pill Count',
                  'expiration_date': 'Expiration Date'}

class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

learning_logs/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from .models import Topic
from .forms import ContactForm
from .forms import TopicForm

import googlemaps
import random
import os

# Create your views here.
def index(request):
    """The home page for Silver"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all medications."""
    topics = Topic.objects.filter(owner=request.user).order_by('expiration_date')
    context = {'topics': topics }
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single medication and all its entries"""
    medication = get_object_or_404(Topic, id=topic_id)
    
    # Make sure the topic belongs to the current user.
    if medication.owner != request.user:
        raise Http404

    context = {'medication': medication}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:medications'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def refill(request, zip_code, medication_id):
    """Show refill options for a specific medication"""
    medication = get_object_or_404(Topic, id=medication_id)

    # Make sure the topic belongs to the current user.
    if medication.owner != request.user:
        raise Http404

    def get_price(pharm_id, medication):
        random.seed(pharm_id + medication_id)

        orig_price = medication.price

        buffer = orig_price*0.2
        return random.uniform(orig_price-buffer, orig_price+buffer)

    def show_pharmacies():
        gmaps = googlemaps.Client(key=os.getenv('GOOGLE_PLACES_API'))
        geocode_result = gmaps.geocode(zip_code)
        coords = geocode_result[0]['geometry']['location']
        pharmacies_results = gmaps.places(query='', location=coords, type='pharmacy', radius=5)['results']

        for pharmacy in pharmacies_results:
            pharmacy['price'] = get_price(pharmacy['id'], medication)

        return sorted(pharmacies_results, key=lambda k: k['price'])

    context = {'medication': medication, 'pharmacies': show_pharmacies(), 'zip_code': zip_code}
    return render(request, 'learning_logs/refill.html', context)

def support(request):
    """The support page for Silver"""
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            # try:
            #     send_mail(subject, message, email, ['admin@example.com'])
            # except BadHeaderError:
            #     return HttpResponse('Invalid header found.')
            return render(request, 'learning_logs/support.html', {'success': True, 'form': ContactForm()})
    return render(request, 'learning_logs/support.html', {'form': form})

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm 

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(reverse('learning_logs:medications'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Silver</title>

        <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" type="text/css" href="{% static "learning_logs/footer.css" %}">
        <link rel="icon" type="image/png" href="{% static "learning_logs/favicon.ico" %}" />
    </head>


    <body>
        <!-- Static Navbar -->
        <nav class="navbar navbar-default bg-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                  <a class="navbar-brand" align="middle" href="{% url 'learning_logs:index' %}"><img src="{% static "learning_logs/Cerner_RGB_Standard_horizontal-1.png" %}" width="100px"></a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">

                <div class="text-primary"></div>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a class="words">Welcome Back, {{ user.username }}</a></li>
                            <li><a href="{% url 'learning_logs:medications' %}"><header>Medications</header></a></li>
                            <li><a href="{% url 'learning_logs:support' %}">Support</a></li>
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                            <li><a href="{% url 'learning_logs:support' %}">Support</a></li>
                            <li><a href="{% url 'users:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div> <!--/.nav-collapse-->
            </div>
        </nav>

        <div class="container">
            <div class="container-sp">
                <div class="page-header">
                    {% block header %} {% endblock header %}
                </div>
                <div>
                    {% block content %} {% endblock content %}
                </div>
            </div>
        </div>
        <div class="holder"></div>
    </body>

<div class="footer text-center">
  <p>Copyright © 2018 Cerner Corporation.  All Rights Reserved.</p>
</div>

</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block header %}
        <img src="{% static "learning_logs/Final image.jpg" %}" width="100%">

  <div class="holder text-center">

  <h2>CREATORS OF SILVER</h2>
    <div class="row"></div>
  <tr>
    <th>Gregg Allnutt</th>
    <th> / </th>
    <th>Pratik Vaidya</th>
    <th> / </th>
    <th>Lucas Kern</th>
    <th> / </th>
    <th>Jack Sullivan</th>
  </tr>
  </div>
</div>
{% endblock header %}

{% block content %}

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block header %}
    <h2>Add a New Medication</h2>
{% endblock header %}

{% block content %}
    <style>
        /* In order to place the tracking correctly */
        canvas.drawing, canvas.drawingBuffer {
            position: absolute;
            left: 33%;
        }
    </style>
    <div style="text-align: center" id="scanner-container"></div>
    <script src="{% static "learning_logs/quagga.min.js" %}"></script>

    <form action="{% url 'learning_logs:new_medication' %}" method='post' class="form">
        
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Medication</button>
        {% endbuttons %}
    
    </form>

    <script>

        startScanner()

        document.onkeydown = function(event){
            if (event.altKey) {
                Quagga.stop()
                document.querySelector('#scanner-container').style.display = "None"
                fields = document.querySelectorAll('input.form-control')
                fields[0].value = 'Nitroglycerin'
                fields[1].value = 2.5
                fields[2].value = 'mg'
                fields[3].value = 'Dr. Adnan Chhatriwalla'
                fields[4].value = 'Walgreens'
                fields[5].value = 292.44
                fields[6].value = '01/20/2019'
            }
        };

        function startScanner() {
            Quagga.init({
                inputStream: {
                    name: "Live",
                    type: "LiveStream",
                    target: document.querySelector('#scanner-container'),
                    constraints: {
                        width: 480,
                        height: 320,
                        facingMode: "environment"
                    },
                },
                decoder: {
                    readers: [
                        "upc_reader",
                        "upc_e_reader",
                        "i2of5_reader"

                    ]
                },

            }, function (err) {
                if (err) {
                    console.log(err);
                    return
                }

                console.log("Initialization finished. Ready to start");
                Quagga.start();

                // Set flag to is running
                _scannerIsRunning = true;
            });

            Quagga.onProcessed(function (result) {
                var drawingCtx = Quagga.canvas.ctx.overlay,
                    drawingCanvas = Quagga.canvas.dom.overlay;

                if (result) {
                    if (result.boxes) {
                        drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                        result.boxes.filter(function (box) {
                            return box !== result.box;
                        }).forEach(function (box) {
                            Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 2 });
                        });
                    }

                    if (result.box) {
                        Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 2 });
                    }

                    if (result.codeResult && result.codeResult.code) {
                        Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
                    }

                }
            });


            Quagga.onDetected(function (result) {
                var div = document.getElementById('results-container');
                div.innerHTML += " " + result.codeResult.code;
            });
        }
    </script>
{% endblock content %}

learning_logs/templates/learning_logs/refill.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>{{ medication.name }}</h2>
    <a href="{% url 'learning_logs:medications'%}">Back to Medications</a>
{% endblock header %}

{% block content %}
    <div class="container">
        <h4>Medication Details</h4>
        <div class="table-responsive" style="padding-bottom: 10px;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Medication</th>
                        <th>Dose</th>
                        <th>Pill Count</th>
                        <th>Prescriber</th>
                        <th>Pharmacy</th>
                        <th>Price</th>
                        <th>Expiration Date</th>
                        <th>Prescription Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ medication.name }}</td>
                        <td>{{ medication.dose }} {{ medication.dose_units }}</td>
                        <td>{{ medication.pill_count }}</td>
                        <td>{{ medication.prescriber }}</td>
                        <td>{{ medication.pharmacy }}</td>
                        <td>${{ medication.price|floatformat:2 }}</td>
                        <td>{{ medication.expiration_date }}</td>
                        <td>
                            <strong>
                                <span class="text-{{ medication.expiration_status }}">
                                    {{ medication.expiration_text }}
                                </span>
                            </strong>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <h4 class="tp-2">Local Pharmacies</h4>

        <div class="input-group input-group-sm col-xs-3">
            <span class="input-group-addon">Zip Code</span>
            <input type="text" class="form-control" placeholder="ex. 64108">
            <span class="input-group-btn"><button id='search' type="button" class="btn btn-default">Go</button></span>
        </div>

        <div class="row">
            <div class="col-lg-8">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pharmacy in pharmacies %}
                            <tr>
                                <td>{{ pharmacy.name }}</td>
                                <td>{{ pharmacy.formatted_address }}</td>
                                <td>${{ pharmacy.price|floatformat:2 }}</td>
                            </tr>
                        {% empty %}
                            <p>Unfortunately, we are unable to find any local pharmacies.</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4" style="text-align:center">
                <iframe class="mt-5" height="450" frameborder="0" style="border:0; margin: 36px 25px;"
                        src="https://www.google.com/maps/embed/v1/search?q=pharmacies%20near%20{{ zip_code }}&key=AIzaSyB9VuR8O5CajyGfVzn3mO1HNG2bj9y89ZQ">
                </iframe>
            </div>
        </div>

    </div>

    <script>
    document.querySelector('#search').addEventListener('click', function() {
        zip_code = document.querySelector('input').value;
        if (!zip_code) { zip_code = '64108' };
        document.location.pathname = 'medications/refills/' + zip_code + '/' + {{ medication.id }};
    });

    </script>
{% endblock content %}

learning_logs/templates/learning_logs/support.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block header %}
    <h2>Contact Us</h2>
{% endblock header %}

{% block content %}
    <div class="info-text"></div>
    <p>
        Hello, welcome to Silver, the all in one application to save you money and protect your body from potentially toxic
        medications. We strive to give all users the best user experience possible. If you are having any technical
        difficulties, need to ask questions about the site, or just want to send use a thought on how to improve your experience
        while using our application just drop us a message below!
    </p>
    </div>
    {% if success %}
        <div class="alert alert-success">
            <strong>Thank you!</strong> We'll be in touch shortly.
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>{{ medication.name }}</h2>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class=""
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Medication</th>
                    <th>Dose</th>
                    <th>Pill Count</th>
                    <th>Prescriber</th>
                    <th>Pharmacy</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ medication.name }}</td>
                    <td>{{ medication.dose }} {{ topic.dose_units }}</td>
                    <td>{{ medication.pill_count }}</td>
                    <td>{{ medication.prescriber }}</td>
                    <td>{{ medication.pharmacy }}</td>
                    <td>${{ medication.price|floatformat:2 }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Medications</h2>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Medication</th>
                        <th>Dose</th>
                        <th>Pill Count</th>
                        <th>Prescriber</th>
                        <th>Pharmacy</th>
                        <th>Price</th>
                        <th>Expiration Date</th>
                        <th>Prescription Status</th>
                        <th>Refill Prescriptions</th>
                    </tr>
                </thead>
                <tbody>
                {% for topic in topics %}
                    <tr>
                        <td>{{ topic.name }}</td>
                        <td>{{ topic.dose }} {{ topic.dose_units }}</td>
                        <td>{{ topic.pill_count }}</td>
                        <td>{{ topic.prescriber }}</td>
                        <td>{{ topic.pharmacy }}</td>
                        <td>${{ topic.price|floatformat:2 }}</td>
                        <td>{{ topic.expiration_date }}</td>
                        <td><strong><span class="text-{{ topic.expiration_status }}">{{ topic.expiration_text }}</span></strong></td>
                        <td>
                            <a href="{% url 'learning_logs:refill' 64108 topic.id %}">
                                <button type="button" class="btn btn-primary btn-sm">
                                    Compare Prices
                                </button>
                            </a>
                        </td>

                    </tr>
                {% empty %}
                    <p>No medications have been added yet.</p>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'learning_logs:new_medication' %}">
        <button type="button" class="btn btn-primary btn-lg">
            Add a New Medication
        </button>
    </a>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Login to your Account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Log In</button>
        {% endbuttons %}
        
        <input type="hidden" name="next" value="{% url 'learning_logs:medications' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Register for an Account</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}